In [22]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

In [23]:
model_name = "bert"

time_list = [0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11, 0.12, 0.13, 0.14, 0.15]
arr_rate_list = [30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90]

if model_name == 'bert':
    time_list = [1, 1.2, 1.4, 1.6, 1.8, 2, 2.2, 2.4]
    arr_rate_list = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]

In [24]:
sampled_pwds = pd.read_csv("tl/e24_random_10_pwmds.csv")

In [25]:
sampled_pwds = list(sampled_pwds['powermode'].values)

In [26]:
all_data = pd.read_csv(f"{model_name}_infer_data_final.csv")

In [27]:
all_data['powermode'] = all_data['cores'].astype(str) + "_" + all_data['cpu'].astype(str) + "_" + all_data['gpu'].astype(str) + "_" + all_data['mem'].astype(str)

In [28]:
# filter out the sampled pwds
all_data = all_data[all_data['powermode'].isin(sampled_pwds)]

In [29]:
all_data.reset_index(drop=True, inplace=True)

In [30]:
nn_pareto_df = pd.read_csv(f"/home/saisamarth/exp/tl/e24_merged_observed_predicted_{model_name}_NN_infer_sampled_50.csv")

In [31]:
nn_pareto_df = nn_pareto_df[nn_pareto_df['powermode'].isin(sampled_pwds)]

In [32]:
nn_pareto_df.reset_index(inplace=True, drop=True)

In [33]:
nn_pareto_df

,powermode,bs,observed_time,predicted_time,observed_power,predicted_power
0,12_422400_522750000_2133000000,1,157.314720,445.62045,22.6880,25.048338
1,4_422400_930750000_3199000000,1,164.788414,209.55309,24.5795,32.944366
2,4_729600_114750000_2133000000,1,563.398376,1469.51940,15.7650,15.796767
3,8_1036800_114750000_3199000000,1,577.068817,1065.43250,17.2700,17.474821
4,12_1036800_726750000_2133000000,1,103.590687,455.11853,29.0035,31.352797
5,8_1344000_114750000_665600000,1,557.418243,1837.81910,15.3530,15.226015
6,8_1344000_114750000_2133000000,1,553.883423,542.31525,16.1660,16.391232
7,8_1344000_522750000_665600000,1,238.206413,533.25446,19.8780,19.455263
8,12_2201600_114750000_2133000000,1,552.249084,838.77320,17.3640,17.857962
9,8_2201600_318750000_3199000000,1,202.397903,454.03130,23.8380,23.775625
10,12_422400_522750000_2133000000,4,554.678955,585.62430,26.8040,26.291265
11,4_422400_930750000_3199000000,4,323.104858,312.77130,41.6920,35.336803
12,4_729600_114750000_2133000000,4,2150.208984,2380.92300,16.5650,16.531498
13,8_1036800_114750000_3199000000,4,2117.261841,2255.12230,17.8700,18.161734
14,12_1036800_726750000_2133000000,4,402.142288,576.85046,33.1180,32.451122
15,8_1344000_114750000_665600000,4,2116.978394,2512.98100,16.0650,15.817806
16,8_1344000_114750000_2133000000,4,2095.649658,1714.63020,16.9690,16.979206
17,8_1344000_522750000_665600000,4,1006.486664,1039.67290,20.2840,20.291597
18,12_2201600_114750000_2133000000,4,2106.194458,2196.31150,18.2690,18.432240
19,8_2201600_318750000_3199000000,4,775.365479,758.87330,25.4000,24.589832
20,12_422400_522750000_2133000000,8,914.760345,829.48865,28.1090,27.100843
21,4_422400_930750000_3199000000,8,600.276215,504.37564,41.9755,37.692690
22,4_729600_114750000_2133000000,8,4077.566895,4190.18070,16.5680,16.782640
23,8_1036800_114750000_3199000000,8,4062.864868,4200.34470,17.7760,18.162888
24,12_1036800_726750000_2133000000,8,714.433197,779.60535,33.6200,32.906727
25,8_1344000_114750000_665600000,8,4036.872559,4262.49100,16.0680,16.039900
26,8_1344000_114750000_2133000000,8,4059.097290,3836.46020,16.9690,17.104360
27,8_1344000_522750000_665600000,8,1891.217224,1755.27820,20.0800,20.445255
28,12_2201600_114750000_2133000000,8,4051.997314,4235.56250,18.1750,18.629507
29,8_2201600_318750000_3199000000,8,1512.941772,1285.63130,25.1030,25.308353
30,12_422400_522750000_2133000000,16,2080.650757,1592.99900,28.0020,27.214201
31,4_422400_930750000_3199000000,16,1259.427673,1007.51210,39.2230,39.651016
32,4_729600_114750000_2133000000,16,8580.166016,8572.80600,16.6660,16.539970
33,8_1036800_114750000_3199000000,16,8568.887207,8355.77600,17.8730,18.060547
34,12_1036800_726750000_2133000000,16,1520.882446,1370.99280,33.2190,32.835888
35,8_1344000_114750000_665600000,16,8392.454102,8888.00700,16.0650,15.935838
36,8_1344000_114750000_2133000000,16,8384.607910,8105.78170,17.0700,16.884962
37,8_1344000_522750000_665600000,16,3898.854980,3435.18240,20.2800,20.182636
38,12_2201600_114750000_2133000000,16,8434.962891,8271.27050,18.2720,18.577637
39,8_2201600_318750000_3199000000,16,3028.897827,2670.38820,25.6010,25.500662
40,12_422400_522750000_2133000000,32,4088.166626,4220.68550,28.4100,27.733368
41,4_422400_930750000_3199000000,32,2495.038452,2482.99100,43.0780,42.623480
42,4_729600_114750000_2133000000,32,16719.571289,16705.81000,16.6630,16.339745
43,8_1036800_114750000_3199000000,32,16402.595703,16240.70600,17.8760,18.006067
44,12_1036800_726750000_2133000000,32,3110.397705,3105.24630,33.2110,32.841330
45,8_1344000_114750000_665600000,32,16662.943359,17227.19700,16.0620,16.046432
46,8_1344000_114750000_2133000000,32,16660.007812,16214.94400,16.9690,16.690718
47,8_1344000_522750000_665600000,32,8001.513428,7533.32670,20.2800,20.166939
48,12_2201600_114750000_2133000000,32,16524.200195,16070.86500,18.1720,18.807390
49,8_2201600_318750000_3199000000,32,6086.679932,6690.81250,25.4000,25.520784

In [34]:
power_list = np.arange(10, 51, 1)

In [35]:
def find_optimal_pm(df, pmax, tmax, a):
    #filter rows where interleaved_power<=pmax, sort in ascending order of interleaved_time
    all_data = df.copy()
    df = df[df['observed_power'] <= pmax]
    df['time_scaled'] = df['observed_time']/1000.0
    df['time_cond1'] = (df['bs'].astype(int))/a + df['time_scaled']
    df['time_cond2'] = df['time_scaled']*a

    df = df[(df['time_cond1'] <= tmax)]
    df = df[(df['time_cond2'] <= df['bs'])]
    
    df = df.sort_values(by='time_scaled', ascending=True)

    if df.empty:
        temp_data = all_data[all_data['observed_power'] > pmax]
        if temp_data.empty:
            all_data = all_data.sort_values(by='observed_time', ascending=True)
            return all_data.iloc[0]['powermode'], all_data.iloc[0]['bs'], all_data.iloc[0]['observed_time'], all_data.iloc[0]['observed_power'], 0
        else:
            temp_data = temp_data.sort_values(by='observed_time', ascending=True)
            return temp_data.iloc[0]['powermode'], temp_data.iloc[0]['bs'], temp_data.iloc[0]['observed_time'], temp_data.iloc[0]['observed_power'], 0
            
    else:
        return df.iloc[0]['powermode'], df.iloc[0]['bs'], df.iloc[0]['observed_time'], df.iloc[0]['observed_power'], 1

In [36]:
def find_optimal_pm_nn(df, pmax, tmax, a):
    #filter rows where interleaved_power<=pmax, sort in ascending order of interleaved_time
    all_data = df.copy()
    df = df[df['predicted_power'] <= pmax]
    df['time_scaled'] = df['predicted_time']/1000.0
    df['time_cond1'] = (df['bs'].astype(int))/a + df['time_scaled']
    df['time_cond2'] = df['time_scaled']*a

    df = df[(df['time_cond1'] <= tmax)]
    df = df[(df['time_cond2'] <= df['bs'])]
    
    df = df.sort_values(by='time_scaled', ascending=True)
    if df.empty:
        temp_data = all_data[all_data['predicted_power'] > pmax]
        if temp_data.empty:
            all_data = all_data.sort_values(by='predicted_time', ascending=True)
            return all_data.iloc[0]['powermode'], all_data.iloc[0]['bs'], all_data.iloc[0]['observed_time'], all_data.iloc[0]['observed_power'], 0
        else:
            temp_data = temp_data.sort_values(by='predicted_time', ascending=True)
            return temp_data.iloc[0]['powermode'], temp_data.iloc[0]['bs'], temp_data.iloc[0]['observed_time'], temp_data.iloc[0]['observed_power'], 0
    #return top1 powermode, time and power
    return df.iloc[0]['powermode'], df.iloc[0]['bs'], df.iloc[0]['observed_time'], df.iloc[0]['observed_power'], 1

In [37]:
random_result_df = pd.DataFrame(columns=['power_budget', 'powermode', 'bs', 'optim_time', 'optim_power','time_budget', 'arr_rate','soln'])

for arr_rate in arr_rate_list:
    for time_budget in time_list:
        for power_budget in power_list:
            try:
                powermode, bs, algo_time, algo_power, soln = find_optimal_pm(all_data, power_budget, time_budget, arr_rate)
                random_result_df.loc[len(random_result_df)] = [power_budget, powermode, bs, algo_time, algo_power, time_budget, arr_rate, soln]
            except:
                print("No Power Mode Found")
                random_result_df.loc[len(random_result_df)] = [power_budget, 0, 0, 0, 0, time_budget, arr_rate, 0]

In [38]:
result_df_nn = pd.DataFrame(columns=['power_budget', 'powermode', 'bs', 'optim_time', 'optim_power', 'time_budget', 'arr_rate','soln'])

for arr_rate in arr_rate_list:
    for time_budget in time_list:
        for power_budget in power_list:
            try:
                powermode, bs, algo_time, algo_power, soln = find_optimal_pm_nn(nn_pareto_df, power_budget, time_budget, arr_rate)
                result_df_nn.loc[len(result_df_nn)] = [power_budget, powermode, bs, algo_time, algo_power, time_budget, arr_rate, soln]
            except:
                print("No Power Mode Found")
                result_df_nn.loc[len(result_df_nn)] = [power_budget, 0, 0, 0, 0, time_budget, arr_rate, 0]

The history saving thread hit an unexpected error (OperationalError('database is locked')).History will not be written to the database.

In [39]:
# merge the two dataframes on power_budget with suffixes (random, nn)
merged_df = pd.merge(random_result_df, result_df_nn, on=['power_budget', 'time_budget', 'arr_rate'], suffixes=('_random', '_nn'))

In [40]:
merged_df

,power_budget,powermode_random,bs_random,optim_time_random,optim_power_random,time_budget,arr_rate,soln_random,powermode_nn,bs_nn,optim_time_nn,optim_power_nn,soln_nn
0,10,12_1036800_726750000_2133000000,1.0,103.590687,29.0035,1.0,1,0,4_422400_930750000_3199000000,1,164.788414,24.5795,0
1,11,12_1036800_726750000_2133000000,1.0,103.590687,29.0035,1.0,1,0,4_422400_930750000_3199000000,1,164.788414,24.5795,0
2,12,12_1036800_726750000_2133000000,1.0,103.590687,29.0035,1.0,1,0,4_422400_930750000_3199000000,1,164.788414,24.5795,0
3,13,12_1036800_726750000_2133000000,1.0,103.590687,29.0035,1.0,1,0,4_422400_930750000_3199000000,1,164.788414,24.5795,0
4,14,12_1036800_726750000_2133000000,1.0,103.590687,29.0035,1.0,1,0,4_422400_930750000_3199000000,1,164.788414,24.5795,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,46,12_1036800_726750000_2133000000,1.0,103.590687,29.0035,2.4,15,0,4_422400_930750000_3199000000,8,600.276215,41.9755,1
4916,47,12_1036800_726750000_2133000000,1.0,103.590687,29.0035,2.4,15,0,4_422400_930750000_3199000000,8,600.276215,41.9755,1
4917,48,12_1036800_726750000_2133000000,1.0,103.590687,29.0035,2.4,15,0,4_422400_930750000_3199000000,8,600.276215,41.9755,1
4918,49,12_1036800_726750000_2133000000,1.0,103.590687,29.0035,2.4,15,0,4_422400_930750000_3199000000,8,600.276215,41.9755,1
4919,50,12_1036800_726750000_2133000000,1.0,103.590687,29.0035,2.4,15,0,4_422400_930750000_3199000000,8,600.276215,41.9755,1

In [41]:
# time = int(time_budget*1000)

In [42]:
merged_df.to_csv(f"{model_name}_random_vs_nn_alt_infer_multi_al.csv", index=False)